### ISSUE TITLE
Ignoring empty macros

### ISSUE THREAD

**Issue by wallace11** [svermeulen/vim-macrobatics#1]
In case you started recording a macro and immidiately stopped it, an empty macro is saved which might "spam" the history. Would be nice if empty macros were ignored, since they serve no purpose.

BTW, nice plugin ;)

**Comment by svermeulen** [comment]
Good idea.  I've changed it to ignore empty macros (and also reset the register to what it was previously)

Thanks!  Glad someone else finds it useful
