### ISSUE TITLE
Not preview with fzf

### ISSUE THREAD

**Issue by v6cc** [svermeulen/vim-macrobatics#12]
I have `export FZF_DEFAULT_OPTS='--layout=reverse --height 80% --preview ...'`  in profile , but get preview error when 
`nmap <leader>ms <plug>(Mac_SearchForNamedMacroAndSelect)`

Can I disable fzf preview for this plug? or preview macro content,  not only name

**Comment by svermeulen** [comment]
I assume you have preview set to something that you use when using fzf on the command line?  Which fails when it tries to use it from within vim?

One way to do this is to override the environment variable `FZF_DEFAULT_OPTS` inside your vim session.  For example:

`:let $FZF_DEFAULT_OPTS='--layout=reverse --height 80%'`

**Comment by svermeulen** [comment]
You might want to leave out the `--height 80%` option though since that causes problems with the way the popup is displayed
