### ISSUE TITLE
Selectable macros from :Macros history

### ISSUE THREAD

**Issue by jmolero** [svermeulen/vim-macrobatics#3]
Thanks for this plugin! I specially like being able to repeat the macro with the dot key.

Would it be possible to extend the `:Macros` command to allow selecting a macro from that list and have it then available to be run with `.` or the `<Plug>(Mac_Play)` mapping?

I know I can use `<Plug>(Mac_RotateForward)` and `<Plug>(Mac_RotateBack)` but I think it would be a nice addition.

**Comment by svermeulen** [comment]
One way to do this currently is to just pass a count to the rotate back command.  I just tested this and it seems to work.  You can display macros with `:Macros` and then find the number of the macro that you want to change to, and then type `5[m` (assuming this number is 5).  I think this is probably better than adding an interactive menu for this.

**Comment by jmolero** [comment]
I'll do that then. Thank you!

**Comment by svermeulen** [comment]
Btw you might also consider using named macros for this kind of thing (added today)

**Comment by jmolero** [comment]
I've just updated my plugins and saw your changes. I'll check it out. Seems similar to what I asked. Thanks!
